---
version: '3.8'
services:
  poc-bff-fastapi:
    build:
      context: .
    container_name: poc-bff-fastapi
    env_file: .env-development
    ports:
      - 3021:3021
      - 50051:50051
      - 50052:50052
    restart: unless-stopped
    volumes:
      - .:/app
